### ISSUE TITLE
how to add Alias to returned field name?

### ISSUE THREAD

**Issue by AzaliyaUfa** [smallrye/smallrye-graphql#2096] opened 2024-04-25 09:31 UTC
with io.smallrye.graphql.client.core.utils.validation.NameValidation.validateFieldName(NameValidation.java:85) it became impossible to return "required_name: name" construction in Field.field

**Comment by mskacelik** [comment] 2024-04-25 10:25
Hmm, it seems that the cause of the exception is the white space after the colon. So deleting it would fix the issue. 

That being said GraphQL specification has listed white space as part of the Ignored Tokens https://spec.graphql.org/draft/#sec-Language.Source-Text.Ignored-Tokens.

So, If you want, we can add this feature so the name validation will ignore all the ignored tokens around the Lexical Tokens.

**Comment by AzaliyaUfa** [comment] 2024-04-25 10:48
thank you so much, it really fixed the problem! 
but adding the option to set an Alias to the field would being great))

**Comment by jmartisk** [comment] 2024-06-10 10:30
fixed by https://github.com/smallrye/smallrye-graphql/pull/2118

**Closed by jmartisk** 2024-06-10 10:30 UTC
