### ISSUE TITLE
Using header as an API method parameter produces "Missing name information for parameter" error

### ISSUE THREAD

**Issue by nilyin** [smallrye/smallrye-graphql#1847] opened 2023-06-06 16:50 UTC
Hi, I am am using GraphQLClientAPI in my Quarkus app to access AWS Appsync service. Particularly, I am setting a request Header as API method parameter as stated here in documentation @ https://smallrye.io/smallrye-graphql/2.2.0/typesafe-client-headers/ as this interface:

```java

@GraphQLClientApi(configKey = "appsync")
public interface IGraphQLClientAPI {
    EcoComponentsList listComponents(String version, @Header(name = "Authorization") String accessToken); 
}

```

and then using this interface in my GraphQLClient.java class like this: 

```java
 @Inject
 IGraphQLClientAPI graphQlClient;

public List<EcoComponent> listComponents(String versionName) {

        String accessToken = sessionManager.getProperty("accessToken");

            List<EcoComponent> result = graphQlClient.listComponents(versionName, accessToken).ecoComponentList().stream()
                    .filter(comp -> comp.versions() != null && comp.versions().size()>0 )
                    .filter(comp -> comp.versions().stream()
                                    .anyMatch(ver -> ver.name() == versionName)
                    )
                    .collect(Collectors.toList());
            return result;
        }

```
when I run my app I get the following Unknown name / Unknown Source error: 

```log
java.lang.RuntimeException: Missing name information for parameter 'arg1' in me.peerf.IGraphQLClientAPI#listComponents.
You can either annotate all parameters with @Name, or compile your source code with the -parameters options, so the parameter names are compiled into the class file and available at runtime.

        at io.smallrye.graphql.client.impl.typesafe.reflection.ParameterInfo.getName(ParameterInfo.java:131)
        at io.smallrye.graphql.client.impl.typesafe.HeaderBuilder.toHeaderName(HeaderBuilder.java:124)
        at io.smallrye.graphql.client.impl.typesafe.HeaderBuilder.resolve(HeaderBuilder.java:120)
        at io.smallrye.graphql.client.impl.typesafe.HeaderBuilder.lambda$build$1(HeaderBuilder.java:58)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at io.smallrye.graphql.client.impl.typesafe.HeaderBuilder.build(HeaderBuilder.java:58)
        at io.smallrye.graphql.client.vertx.typesafe.VertxTypesafeGraphQLClientProxy.invoke(VertxTypesafeGraphQLClientProxy.java:130)
        at io.smallrye.graphql.client.vertx.typesafe.VertxTypesafeGraphQLClientBuilder.invoke(VertxTypesafeGraphQLClientBuilder.java:190)
        at io.smallrye.graphql.client.vertx.typesafe.VertxTypesafeGraphQLClientBuilder.lambda$build$0(VertxTypesafeGraphQLClientBuilder.java:150)
        at com.sun.proxy.$Proxy44.listComponents(Unknown Source)
        at me.peerf.IGraphQLClientAPI_9fe4c5ba9e82c9a0fbefec158e044b6c7bbd88d0_Synthetic_ClientProxy.listComponents(Unknown Source)
        at me.peerf.GraphQLClient.listComponents(GraphQLClient.java:56)


```

it looks like  the  second (header) parameter in function  graphQlClient.listComponents(versionName, accessToken) is not recognized... What am I doing wrong?

2. also I have related question#2: the same documentation link above says I may use specifically '@AuthrizationHeader' for auth, but when I replace basic @Header annotation  in parameter definition with @AuthrizationHeader: 

```java
EcoComponentsList listComponents(String version, @AuthorizationHeader String accessToken);
```

I am receiving "'@AuthorizationHeader' not applicable to parameter" error. How can I apply this type of header in case of dynamic header valuer parametrization?

**Comment by jmartisk** [comment] 2023-06-07 04:42
It's exactly what the exception says - you have to compile your application with the `-parameters` argument to the javac compiler. 
The only way around this is to annotate all parameters with the `@Name` so that the library can deduce the parameter name from it.
Also see https://github.com/smallrye/smallrye-graphql/issues/1714 for a very similar issue.

> I am receiving "'@AuthorizationHeader' not applicable to parameter" error. 

This annotation can only be applied on a method (then only that operation will use the header) or class (then all operations in that API will use it).

> How can I apply this type of header in case of dynamic header valuer parametrization?

I think that `@AuthorizationHeader` doesn't allow dynamic changes. For that you need to either use the plain `@Header`, or use the `TypesafeGraphQLClientBuilder` to build your client dynamically, and then close and re-build it with a different header when the value needs to change.

**Comment by nilyin** [comment] 2023-06-07 11:08
@jmartisk hi, thanks for your answers. the 2nd answer on @AuthorizationHeader is fully addressed and clear.

Regarding the @Name annotation, can you elaborate a bit more and give additional insight, such as:

- which package's @Name to use
- where exactly to use it and how (may be link to examples available?)

for information:  I used @Name from "org.eclipse.microprofile.graphql" package and the only place I was allowed to put it was my wrapper-function of GraphQLClient.java class as shown below:

```java
 @Inject
 IGraphQLClientAPI graphQlClient;

public List<EcoComponent> listComponents(@Name("versionName") String versionName) {

        String accessToken = sessionManager.getProperty("accessToken");

            List<EcoComponent> result = graphQlClient.listComponents(versionName, accessToken).ecoComponentList().stream()
                    .filter(comp -> comp.versions() != null && comp.versions().size()>0 )
                    .filter(comp -> comp.versions().stream()
                                    .anyMatch(ver -> ver.name() == versionName)
                    )
                    .collect(Collectors.toList());
            return result;
        }

```
this way it works, and I've moved further, but I still want to understand the reason why function parameters naming and ordering doesn't simply work in the declared method:

``` java
@GraphQLClientApi(configKey = "appsync")
public interface IGraphQLClientAPI {
    EcoComponentsList listComponents(String version, @Header(name = "Authorization") String accessToken); 
}

```

**Comment by jmartisk** [comment] 2023-06-07 11:23
You'll need to put `@org.eclipse.microprofile.graphql.Name` on all parameters, so 
```
    EcoComponentsList listComponents(@Name("version") String version, @Name("accessToken") @Header(name = "Authorization") String accessToken); 
```

The annotation on the `accessToken` parameter seems unnecessary to me though, if it still throws that error after you annotate `version` then it's probably a bug, can you confirm that?

In any case, the safest and recommended way forward would be to use `-parameters` when compiling.

**Comment by nilyin** [comment] 2023-06-07 16:52
@jmartisk hi, the example with @Name annotation for all parameters as shown in your example above works ok. The code without annotation for @Header parameter as shown below still produces error:

```java
EcoComponentsList listComponents(@Name("version") String version, @Header(name = "Authorization") String accessToken); 
```
so I suppose, it has to be fixed.

for your information I am using:
quarkus 2.16.6.Final
java 11.0.2 2019-01-15 LTS


Thank you very much for your answers. I am unblocked now. It would be also great to add this information on both headers usage (with examples) into the project's documentation page mentioned in my post.

**Comment by jmartisk** [comment] 2023-06-08 06:27
I'll try to add a little fix that will let you use a `@Header` parameter without adding `@Name` to it, because the name isn't actually needed for anything in such case.
But I won't add it as an example into the documentation, rather I'll make it clear that it is a requirement to compile with the `-parameters` flag. The fact that we made it work in some cases without that flag is basically just a little hack and shouldn't be relied upon.

**Comment by jmartisk** [comment] 2023-06-08 06:37
Hmm, hold on, what version of SmallRye GraphQL are you using?
I'm actually trying to reproduce your problem and I can't, this was probably already fixed by via https://github.com/smallrye/smallrye-graphql/pull/1715
The first fixed version is 2.1.0.
Your stack trace also seems to suggest that you're using an older version where this PR isn't incorporated.

**Comment by jmartisk** [comment] 2023-06-08 06:45
I see, you're using Quarkus 2.16.6, then I'm really surprised that you're not using the `-parameters` flag, that is present by default on all Quarkus projects generated by the CLI or code.quarkus.io. With that, you wouldn't have hit this problem at all. You just need to add this under `<plugins>`:

```
<plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${compiler-plugin.version}</version>
        <configuration>
          <compilerArgs>
            <arg>-parameters</arg>
          </compilerArgs>
        </configuration>
      </plugin>
```

**Comment by jmartisk** [comment] 2023-06-08 17:53
I don't think you can separately upgrade the client library version (without nasty hacks that probably wouldn't work anyway), you always get the one that comes with the particular Quarkus version. 
So you will either have to upgrade to Quarkus 3.x or we would have to backport the fix and release a micro update that gets pulled into Quarkus 2.16.x. But given that you can fix your problem by adding `-parameters`, it doesn't seem worth the hassle.

**Closed** 2023-06-08 20:52 UTC
