### ISSUE TITLE
Hibernate JPA fetch type LAZY

### ISSUE THREAD

**Issue by bpalermo** [smallrye/smallrye-graphql#71] opened 2020-03-10 17:21 UTC
How can I properly use JPA relationships?

I'm running Thorntail 2.6.0.Final with smallrye-graphql-servlet 1.0.0

I Have the following classes bellow:

```java
@Entity
@Table(name = "person")
public class Person extends AbstractEntity {

    @Getter @Setter
    private String name;

    @Getter @Setter
    @Column(name = "last_name")
    private String lastName;

    @Getter
    @OneToMany(mappedBy = "person", fetch = FetchType.LAZY)
    private Set<Book> books = new HashSet<>();

}
```
```java
@XmlAccessorType(XmlAccessType.FIELD)
@Entity
@Table(name = "book")
public class Book extends AbstractEntity {

    @Getter
    @Setter
    private String name;

    @Getter @Setter
    @JsonbTransient
    @ManyToOne
    @JoinColumn(name = "fk_person")
    private Person person;

}
```
I request the following query:
```graphql
{
  person(id: 1) {
    name
    books {
      name
    }
  }
}
```
I get the following error from lazy initialization with no session

```graphql
{
  "errors": [
    {
      "message": "Server Error",
      "locations": [
        {
          "line": 4,
          "column": 5
        }
      ],
      "path": [
        "person",
        "books"
      ],
      "extensions": {
        "exception": "org.hibernate.LazyInitializationException",
        "classification": "DataFetchingException"
      }
    }
  ],
  "data": {
    "person": {
      "name": "Bruno",
      "books": null
    }
  }
}
```
And the following stakctrace:

```java
2020-03-10 17:16:06,091 ERROR [io.smallrye.graphql.execution.error.ExceptionHandler] (default task-1) Data Fetching Error: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: io.bpic.poc.graphql.demo.entity.Person.books, could not initialize proxy - no Session
	at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:602)
	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:217)
	at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:581)
	at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:148)
	at org.hibernate.collection.internal.PersistentSet.iterator(PersistentSet.java:188)
	at io.smallrye.graphql.execution.datafetcher.AnnotatedPropertyDataFetcher.get(AnnotatedPropertyDataFetcher.java:74)
	at io.smallrye.graphql.execution.datafetcher.AnnotatedPropertyDataFetcher.get(AnnotatedPropertyDataFetcher.java:59)
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:272)
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:200)
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:74)
	at graphql.execution.ExecutionStrategy.completeValueForObject(ExecutionStrategy.java:656)
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:440)
	at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:390)
	at graphql.execution.ExecutionStrategy.lambda$resolveFieldWithInfo$0(ExecutionStrategy.java:202)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983)
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:201)
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:74)
	at graphql.execution.Execution.executeOperation(Execution.java:165)
	at graphql.execution.Execution.execute(Execution.java:106)
	at graphql.GraphQL.execute(GraphQL.java:623)
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:556)
	at graphql.GraphQL.executeAsync(GraphQL.java:520)
	at graphql.GraphQL.execute(GraphQL.java:450)
	at io.smallrye.graphql.execution.ExecutionService.execute(ExecutionService.java:84)
	at io.smallrye.graphql.execution.ExecutionService$Proxy$_$$_WeldClientProxy.execute(Unknown Source)
	at io.smallrye.graphql.servlet.SmallRyeGraphQLExecutionServlet.doPost(SmallRyeGraphQLExecutionServlet.java:53)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:523)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.swarm.generated.FaviconErrorHandler.handleRequest(FaviconErrorHandler.java:61)
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:91)
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.lang.Thread.run(Thread.java:748)
```

Thanks,
Bruno

**Comment by phillip-kruger** [comment] 2020-03-10 17:43
Hi @bpalermo - Can you share your full app ? Or have a replication app ? Else please share your GraphQLApi class and your JPA properties.

Does this work with REST ?

**Comment by bpalermo** [comment] 2020-03-10 17:53
Unfortunately I can share the app.

Here it is my GraphQLApi

```java
@GraphQLApi
@RequestScoped
public class ProfileGraphQLApi {

    @Inject
    private PersonService service;

    @Query
    @Description("Get a person using the person's Id")
    public Person getPerson(@Name("id") Long id){
        return service.findByPk(id);
    }

    @Query
    public List<Person> getPeople(@Name("limit") Integer limit,
                                  @Name("offset") Integer offset){
        return service.findAll(limit, offset);
    }

}
```
Person service
```java
public class PersonService {

    @PersistenceContext
    EntityManager em;

    public List<Person> findAll(int offset, int limit) {

        CriteriaBuilder cb = em.getCriteriaBuilder();

        CriteriaQuery<Person> query = cb.createQuery(Person.class);
        Root<Person> person = query.from(Person.class);

        query.select(person);

        return em.createQuery(query)
                .setFirstResult(offset)
                .setMaxResults(limit)
                .getResultList();
    }

    public Person findByPk(Long id) {
        return em.find(Person.class, id);
    }
}
```
And persistence.xml

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<persistence xmlns="http://xmlns.jcp.org/xml/ns/persistence"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence http://xmlns.jcp.org/xml/ns/persistence/persistence_2_2.xsd"
             version="2.2">
    <persistence-unit name="DefaultPU">
        <jta-data-source>java:jboss/datasources/MySQLDS</jta-data-source>
        <properties>
            <property name="javax.persistence.schema-generation.database.action" value="none"/>
            <property name="hibernate.dialect.storage_engine" value="innodb"/>
            <property name="hibernate.show_sql" value="false"/>
        </properties>
    </persistence-unit>
</persistence>
```
It doesn't work with REST either.

Thanks!

**Comment by phillip-kruger** [comment] 2020-03-10 17:59
OK, I would love to help, but I can not see anything wrong. Can you create a reproducer ? 
If it also does not work with REST, then the issue is with JPA and not with GraphQL. (But I am still happy to help if you can help me with an app that reproduce the issue)

**Comment by bpalermo** [comment] 2020-03-10 18:21
Thanks @phillip-kruger, I will make a reproducer.

I could get it to work with REST if I add the following line to persistence.xml or change the fetch type to EAGER.
```xml
<property name="hibernate.enable_lazy_load_no_trans" value="true"/>
```
None of them work in GraphQL.

**Comment by bpalermo** [comment] 2020-03-10 18:47
@phillip-kruger you can find it here:

https://github.com/bpalermo/poc-graphql

Just run ./run.sh and make sure you have docker installed.

Thanks!

**Comment by DorianMaliszewski** [comment] 2020-03-11 07:41
Hi @bpalermo ,

The problem with lazy initialization in hibernate is very common. You can set the fetch to eager, or force the fetch in the JPQL.

Here is the SO that show a solution :
https://stackoverflow.com/questions/11746499/how-to-solve-the-failed-to-lazily-initialize-a-collection-of-role-hibernate-ex.

Enjoy, :sweat_smile:

**Comment by bpalermo** [comment] 2020-03-11 09:23
Hi @DorianMaliszewski,

Yes it is. I already tries with fetch = FetchType.EAGER, but it still don work.

Even if it work it would introduce another well known problem, the N + 1 select problem:
https://www.javacodegeeks.com/2018/04/jpa-tips-avoiding-the-n-1-select-problem.html

Thanks,
Bruno

**Comment by phillip-kruger** [comment] 2020-03-31 14:29
Hi @bpalermo .
Can you check against master (i.e build SNAPSHOT on your PC) if this is fixed. 
#98 might have fixed this.

**Comment by phillip-kruger** [comment] 2020-04-03 06:42
Hi @bpalermo . Issue #95 is confirmed fixed in master and I suspect that would also fix your issue.
Can you please confirm ? Thanks

**Comment by bpalermo** [comment] 2020-04-03 10:22
@phillip-kruger sorry for the late reply. Yes it is!

**Comment by phillip-kruger** [comment] 2020-04-03 10:43
Great ! Closing this .

**Closed by phillip-kruger** 2020-04-03 10:43 UTC
