### ISSUE TITLE
Getting class cast exception - class org.glassfish.json.JsonStringImpl cannot be cast to class javax.json.JsonArray 

### ISSUE THREAD

**Issue by adarsh0048** [smallrye/smallrye-graphql#1879] opened 2023-08-02 18:34 UTC
**Query** : 
{
products(first: 4) {
      edges {
        node {
          id
          title
        }
      }
    }
 }
 **Endpoint** : https://snaplogicqa-store.myshopify.com/admin/api/2023-07/graphql.json
 
 **_Not sure why I get_** Failure: class org.glassfish.json.JsonStringImpl cannot be cast to class javax.json.JsonArray (org.glassfish.json.JsonStringImpl and javax.json.JsonArray are in unnamed module of loader org.eclipse.jetty.webapp.WebAppClassLoader @2ab50d73)
 
 This query works fine on postman or curl. Any suggestions / ideas ?

**Comment by jmartisk** [comment] 2023-08-03 07:12
I can't access that endpoint, it's asking me for credentials - any credentials you could share?

Also, I am guessing you're hitting this problem with the client library. Which one, dynamic or typesafe?

Could you also past the whole stack trace of the failure?

A small executable reproducer would be even better...

**Comment by jmartisk** [comment] 2023-11-29 08:28
I can't reproduce this and didn't get any additional info, so I'll close this. If it's still an issue and you can provide more info, please feel free to reopen.

**Closed by jmartisk** 2023-11-29 08:28 UTC
