### ISSUE TITLE
type TimeUnit not found in schema

### ISSUE THREAD

**Issue by asgs** [smallrye/smallrye-graphql#2090] opened 2024-04-18 12:49 UTC
Hello, Team!

First of all, I would like to thank all the authors, contributors, and the users of this implementation. Been using this for a few weeks and it has been a total breeze!

I ran into an issue with using the Java's TimeUnit Enum in one of our schema models to indicate the unit of measurement. The GraphQL schema generation fails with the error below and I couldn't understand how the GraphQL and Java types are mapped

Using the tech stack below

Quarkus v3.9.1
SmallRye GraphQL v2.8.2
JDK v21

Please let me know if you need more info to understand this issue better

Sample Java class

```
public class Monitor {
    private Metric value;
    private Long time;
    private TimeUnit timeUnit = TimeUnit.MILLISECONDS;
}
```
Error
```
Caused by: graphql.AssertException: type TimeUnit not found in schema
        at graphql.Assert.assertNotNull(Assert.java:17)
        at graphql.schema.GraphQLTypeResolvingVisitor.handleTypeReference(GraphQLTypeResolvingVisitor.java:49)
        at graphql.schema.GraphQLTypeResolvingVisitor.visitGraphQLTypeReference(GraphQLTypeResolvingVisitor.java:44)
        at graphql.schema.GraphQLTypeReference.accept(GraphQLTypeReference.java:62)
        at graphql.schema.SchemaTraverser$TraverserDelegateVisitor.enter(SchemaTraverser.java:111)
        at graphql.util.Traverser.traverse(Traverser.java:144)
        at graphql.schema.SchemaTraverser.doTraverse(SchemaTraverser.java:98)
        at graphql.schema.SchemaTraverser.depthFirst(SchemaTraverser.java:88)
        at graphql.schema.SchemaTraverser.depthFirst(SchemaTraverser.java:81)
        at graphql.schema.impl.SchemaUtil.replaceTypeReferences(SchemaUtil.java:105)
        at graphql.schema.GraphQLSchema$Builder.buildImpl(GraphQLSchema.java:941)
        at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:904)
        at io.smallrye.graphql.bootstrap.Bootstrap.generateGraphQLSchema(Bootstrap.java:223)
        at io.smallrye.graphql.bootstrap.Bootstrap.bootstrap(Bootstrap.java:128)
        at io.smallrye.graphql.gradle.tasks.GenerateSchemaTask.generateSchema(GenerateSchemaTask.java:244)
        at io.smallrye.graphql.gradle.tasks.GenerateSchemaTask.generateSchema(GenerateSchemaTask.java:185)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)

**Comment by jmartisk** [comment] 2024-04-18 13:02
Hi. While we could probably get this to work, I would generally advise against using JDK classes (apart from String, Integer, Long,...) directly in your GraphQL APIs. You don't have control over what exactly will be in them, and a simply changing the JDK that you use to build your application could cause unexpected changes or breakages in your application (because it could affect how they are mapped to GraphQL types or break Quarkus' bytecode recording mechanisms). My suggestion would be to create your own enum for this, and if you need to map it to the JDK `TimeUnit`, create a class that maps between them.

**Comment by asgs** [comment] 2024-04-18 13:41
thank you, @jmartisk, for the suggestions!

could you please elaborate on the mapping types?

**Comment by jmartisk** [comment] 2024-04-18 13:47
More explanation: We would have to solve this by changing the `quarkus-smallrye-graphql` extension to automatically add this class into the Jandex index. The problem is that we don't know in advance what application will use what JDK classes (there's currently no way for an application to declare it), and the index has to be finalized before we actually start scanning the GraphQL API. So, that means the extension would have to hardcode a list of JDK classes that 'might' potentially be used, and automatically always add them to the index, and so these classes would be added to the index for all applications, regardless of whether the application uses the class in a GraphQL API or not, and that would slow down the build process for all applications.

Given also the potential compatibility issues I mentioned in the previous comment, I'd be inclined to say it's not worth it, and rather recommend creating your own copies of JDK enums when needed.

> could you please elaborate on the mapping of the types? any sample code/impl would help

I assume this could do it:

```
public enum MyTimeUnit {

    NANOSECONDS,
    MICROSECONDS,
    MILLISECONDS,
    SECONDS,
    MINUTES,
    HOURS,
    DAYS;

    public java.util.concurrent.TimeUnit toJdkTimeUnit() {
        return TimeUnit.valueOf(this.name());
    }
}
```

**Comment by jmartisk** [comment] 2024-04-18 14:04
> wouldn't it be possible to add a pre-processing step to scan the GraphQL APIs (and the corresponding model classes) for any java.* entries and pre-populate the jandex index and then go for another round?

Probably somehow yes, but it would again slow down and complicate the build by building multiple indexes and scanning the app twice. If more people request it and persuade me that it's actually safe and useful to use JDK classes like that, we might consider it :)

Ok let me close it now, let me know if you have any more trouble later.

**Closed by jmartisk** 2024-04-18 14:04 UTC

**Comment by asgs** [comment] 2024-04-18 21:37
sure thing, @jmartisk 

thank you again. Much appreciated!

**Comment by phillip-kruger** [comment] 2024-04-18 23:16
What about using an adapter ?  https://quarkus.io/guides/smallrye-graphql#adapt-with

**Comment by jmartisk** [comment] 2024-04-19 06:11
That would still require the class to be in the index I think

**Comment by phillip-kruger** [comment] 2024-04-19 06:12
Yea but the adaptor should add it to the index, so that should be ok

**Comment by phillip-kruger** [comment] 2024-04-19 06:13
In the Quarkus extension we update the index with all classes from the adaptor
