### ISSUE TITLE
The @Key Federation Directive should not be set on "Input" Object

### ISSUE THREAD

**Issue by vitomanu96** [smallrye/smallrye-graphql#1867] opened 2023-07-19 15:56 UTC
```
@Key(fields = "codice")
public class Comune {

    @Id
    private String codice;
}
```

I use the Comune object for both querying and mutating data, and the @key annotation should not be set in the schema.graphql file within the ComuneInput definition

```
input ComuneInput @key(fields : "codice") {
  codice: ID
}
```

**Comment by francescopochi** [comment] 2023-07-20 10:20
Same problem here.

**Comment by A1berto** [comment] 2023-07-20 10:27
Having the same issue ^

**Comment by phillip-kruger** [comment] 2023-07-21 00:40
Thanks for this ! @jmartisk @mskacelik can you have a look ? Maybe @t1 ?

**Comment by jmartisk** [comment] 2023-08-02 13:13
@mskacelik is looking. Turns out this is not only a problem for `@Key`, we put directives all over the place regardless of element types on which a particular directive is allowed. So we're going to take a wider approach to the fix.

**Comment by vitomanu96** [comment] 2023-08-02 14:23
> @mskacelik is looking. Turns out this is not only a problem for `@Key`, we put directives all over the place regardless of element types on which a particular directive is allowed. So we're going to take a wider approach to the fix.

@mskacelik if you need help, contact me.

**Comment by mskacelik** [comment] 2023-08-04 08:05
@vitomanu96 can you please check PR if everything works as intended? Hopefully It should be fixed now.
https://github.com/smallrye/smallrye-graphql/pull/1878

**Closed** 2023-08-08 06:51 UTC
