### ISSUE TITLE
Failed to link SmallRyeContextThreadContextProvider: org/eclipse/microprofile/context/spi/ThreadContextProvider

### ISSUE THREAD

**Issue by michaelsonnleitner** [smallrye/smallrye-graphql#567] opened 2020-12-10 08:21 UTC
With Version 1.19.0 I am getting following error during startup in JBoss EAP 7.3.2. With 1.17.0 no error is shown.
any ideas?

```
09:18:09,565 WARN  [org.jboss.modules.define] (Weld Thread Pool -- 9) Failed to define class io.smallrye.graphql.execution.context.SmallRyeContextThreadContextProvider in Module "deployment.d-business-war-1.20.0-SNAPSHOT.war" from Service Module Loader: java.lang.NoClassDefFoundError: Failed to link io/smallrye/graphql/execution/context/SmallRyeContextThreadContextProvider (Module "deployment.d-business-war-1.20.0-SNAPSHOT.war" from Service Module Loader): org/eclipse/microprofile/context/spi/ThreadContextProvider
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:833)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:424)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:555)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:339)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:126)
	at org.jboss.modules.Module.loadModuleClass(Module.java:731)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:247)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at org.jboss.as.weld.WeldModuleResourceLoader.classForName(WeldModuleResourceLoader.java:68)
	at org.jboss.weld.bootstrap.AnnotatedTypeLoader.loadClass(AnnotatedTypeLoader.java:82)
	at org.jboss.weld.bootstrap.AnnotatedTypeLoader.loadAnnotatedType(AnnotatedTypeLoader.java:62)
	at org.jboss.weld.bootstrap.FastAnnotatedTypeLoader.loadAnnotatedType(FastAnnotatedTypeLoader.java:108)
	at org.jboss.weld.bootstrap.BeanDeployer.addClass(BeanDeployer.java:87)
	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:55)
	at org.jboss.weld.bootstrap.ConcurrentBeanDeployer$1.doWork(ConcurrentBeanDeployer.java:52)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
	at org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:485)

09:18:09,565 INFO  [org.jboss.weld.Bootstrap] (Weld Thread Pool -- 9) WELD-000119: Not generating any bean definitions from io.smallrye.graphql.execution.context.SmallRyeContextThreadContextProvider because of underlying class loading error: Type Failed to link io.smallrye.graphql.execution.context.SmallRyeContextThreadContextProvider (Module "deployment.d-business-war-1.20.0-SNAPSHOT.war" from Service Module Loader): org.eclipse.microprofile.context.spi.ThreadContextProvider not found.  If this is unexpected, enable DEBUG logging to see the full error.
09:18:09,986 INFO  [org.jboss.weld.Bootstrap] (Weld Thread Pool -- 4) WELD-000119: Not generating any bean definitions from io.smallrye.graphql.cdi.tracing.TracingService because of underlying class loading error: Type io.opentracing.Tracer from [Module "deployment.d-business-war-1.20.0-SNAPSHOT.war" from Service Module Loader] not found.  If this is unexpected, enable DEBUG logging to see the full error.
09:18:13,237 WARN  [org.jboss.weld.Bootstrap] (Weld Thread Pool -- 4) WELD-000167: Class at.rsg.drb.e2e.apift.util.BaseCacheResolverFactory is annotated with @Dependent but it does not declare an appropriate constructor therefore is not registered as a bean!
```

And while executing a query I am getting

```
java.lang.NoClassDefFoundError: org/eclipse/microprofile/context/ThreadContext
```

**Comment by phillip-kruger** [comment] 2020-12-10 08:48
Can you share a reproducer ? Have you tried with latest version ?

**Comment by michaelsonnleitner** [comment] 2020-12-10 08:55
I think the problem is, that in my EAP 7.3.2 Microprofile Context Propagation is not included (https://projects.eclipse.org/projects/technology.microprofile/releases/context-propagation-1.0#:~:text=MicroProfile%20Context%20Propagation%201.0%20provides,when%20running%20the%20CompletionStage%20action.) and you are using it since 1.19.0

**Comment by jmartisk** [comment] 2020-12-10 09:14
Indeed, Context Propagation is now expected to be present. 
If you use the WildFly feature pack (https://github.com/wildfly-extras/wildfly-graphql-feature-pack) you will get context propagation included by installing the feature pack, but only with version 1.1.0 which is not out yet, but I'm planning to release it pretty soon.
I haven't really tested it with EAP though, so I'm not sure it will work flawlessly.

If nothing else helps, we could make context propagation optional, so it would not throw any warnings, but obviously you wouldn't get your contexts propagated into asynchronous operations.

**Comment by jmartisk** [comment] 2020-12-10 09:18
One more hack worth trying would be to just include the SmallRye Context Propagation jar in your deployment. I think it won't work properly without the subsystem integration, but if you're not using any async operations, it *might* work, because you won't need any context propagated (but again I'm not 100% sure)

**Comment by michaelsonnleitner** [comment] 2020-12-10 09:18
optional would be nice.

**Comment by jmartisk** [comment] 2020-12-10 10:31
Is switching to the WildFly GraphQL feature pack not an option for you? I could release `1.1.0.Beta1` for you pretty much immediately, that would include SmallRye GraphQL 1.0.19, and has Context Propagation in it as well.  And it has all the wiring needed to get GraphQL working by simply including a `@GraphQLApi` class in your deployment (I suppose that without it, you manually have to install an execution service and maybe some other stuff).
I just need to figure out how to install it into EAP instead of WildFly, but I suppose it won't be that difficult.

**Comment by michaelsonnleitner** [comment] 2020-12-10 11:06
I have already the execution servlet in my application. I am not responsible for our server configuration. 

in short words: it is not possible for me to tell the datacenter to use 1.1.0.Beta1 that would be a long running process...

currently I am running smallrye-graphql 1.18.0 and this works for me - but I am currently on the way to production stage

**Comment by phillip-kruger** [comment] 2020-12-10 12:39
Hi @michaelsonnleitner - Context propagation is needed for us to 1) make sure the batch feature works when using RequestScope and 2) make sure Async methods works. So it's not a optional feature. I would suggest that you open a ticket with EAP and ask them that you want support for GraphQL in EAP. Alternatively you can try and get it to work by including the Context propagation libraries yourself, or you can stay on an older version of SmallRye GraphQL. I am closing this issue, if you believe this is still a bug you are welcome to reopen. Thanks :)

**Closed by phillip-kruger** 2020-12-10 12:39 UTC
