### ISSUE TITLE
Using Panache Reactive and reactive pg client gives CompletionException on 5-th request

### ISSUE THREAD

**Issue by Atoiebai** [smallrye/smallrye-graphql#1386] opened 2022-05-07 19:32 UTC
When i am running my service i am able to send only 4 request , after it i will get Timeout with CompletionException from my service. I am not the first with this trouble and an error is always reproducible, you should just restart a service to get exactly same behavior for each request . While substituting reactive-pg driver for classic jdbc everything becomes fine.
Same issue: https://stackoverflow.com/questions/70939493/why-am-i-getting-timeout-exception-after-4-requests-to-database
 also i changed reactive panache to panache-orm*

**Comment by zbhavyai** [comment] 2022-05-09 19:42
Possible duplicate of [https://github.com/quarkusio/quarkus/issues/21111](https://github.com/quarkusio/quarkus/issues/21111).

**Comment by phillip-kruger** [comment] 2022-05-09 23:56
Fixed with https://github.com/quarkusio/quarkus/pull/25194. Will be available in 2.10

**Closed by phillip-kruger** 2022-05-09 23:56 UTC
