### ISSUE TITLE
Default Support for Limit and Page of Resolvers returing Lists 

### ISSUE THREAD

**Issue by michaelsonnleitner** [smallrye/smallrye-graphql#456] opened 2020-10-09 09:13 UTC
Limit or the possibility to page a GraphQL Resolver is a common usecase.

It would be nice if this is a standard feature in the underlying graphql invoker of resolvers implemetation

**following query:**
```
query{
  p1: person(id: 1) {
    adresses(limit: 15, start: 0)
    { 
       street
    }
  }
}
```

**should work with following resolver:**
```
@GraphQLApi
public class PersonResource {

   @Inject
   AdressService adressService ;
   @Inject
   PersonRestApi personRestApi;

    @Query
    public Person getPerson(@Name("id") long id) throws ApiException, InterruptedException {
       Thread.sleep(2000);
        return personRestApi.load(id);
    }
   public List<Adress> getAdresses(@Source Person p) { 
      return adressService .getAdresses(p.getId());
   }
}
```

**Result:**
```
person 1 with the first 15 assigned adresses
```

The invoker of PersonResource .getAdresses(..) should limit and page the returning List<Adress> from 0 to 15. (imaging you have an legacy AdressService which can *NOT* limit, order, page the result on its own)

**Comment by phillip-kruger** [comment] 2020-10-10 09:56
Linked to eclipse/microprofile-graphql#29.
We can support this in SmallRye before we move this to the spec. Again, PR's are welcome :)
Duplicate of #455 ?

**Comment by michaelsonnleitner** [comment] 2020-10-12 08:31
it was a duplicate sry.

**Closed** 2020-10-12 08:31 UTC
Labels: Server, duplicate, enhancement
