### ISSUE TITLE
GET requests

### ISSUE THREAD

**Issue by t1** [smallrye/smallrye-graphql#283] opened 2020-06-09 03:54 UTC
Maybe I get something wrong, but it could be that GET requests don't work exactly as they [should](https://graphql.org/learn/serving-over-http/#get-request). I expected a query to look like this:

```
http://localhost:8080/graphql-java-experiment/graphql?query={heroes{name}}
```

But I have to do this:

```
http://localhost:8080/graphql-java-experiment/graphql?query={"query":"{heroes{name}}"}
```

I didn't find any tests in the TCK.

BTW: why are GET requests disabled by default?

**Comment by phillip-kruger** [comment] 2020-06-09 06:54
Yea there is still some work to be done here. The spec also still need to define this. The way I have done it (not sure if that is correct) is to allow you to add the whole json payload (that you would put in the body of a POST) in the get. 

They are disabled by default because you should use POST ! (joking) It's for security reasons. Any data in the url are exposed and visible on proxy servers and logs. We need to also mention this in the spec when we add the HTTP section

**Comment by t1** [comment] 2020-06-10 03:49
[graphql.org](https://graphql.org/learn/serving-over-http/#get-request) says that GET requests have up to three http query variables: `query`, `variables`, and `operationName`, so it should not be nested in a JSON object itself.

I don't fully subscribe to the security argument. Actually http proxies have access also to the body. It's true that they often do log the query parameters, but not the body. But that's true for REST services as well, and it's obviously not a problem there. Maybe we should limit GET requests to queries instead? I think that is more what people would expect.

**Comment by t1** [comment] 2020-06-10 05:39
I've created https://github.com/eclipse/microprofile-graphql/issues/258

**Comment by phillip-kruger** [comment] 2020-06-10 06:46
If you don't buy the argument, you can use configuration to allow GET :)
For REST it was always an issue at banks and other financial institutions where I worked. 
There is already https://github.com/eclipse/microprofile-graphql/issues/179 that I think should cover all these topics.

**Comment by phillip-kruger** [comment] 2020-06-10 06:48
And this is possibly a duplicate of #69 ?

**Closed** 2020-06-10 06:57 UTC
