### ISSUE TITLE
@link not working for quarkus

### ISSUE THREAD

**Issue by robp94** [smallrye/smallrye-graphql#2154] opened 2024-08-01 13:03 UTC
The GraphQL test works, so maybe the error is somewhere in quarkus/implementation-cdi? But I can not find it.

Quarkus is just the code start with enabled federation via application parameters. Furthermore, I added the @link like in the link tests.

```
@GraphQLApi
@Link(url = FEDERATION_SPEC_URL + "/v2.1", _import = { @Import(name = "@policy") })
public class HelloGraphQLResource {
```
in the Schema builder the link is not included, in the index view there is a link annotation.
![image](https://github.com/user-attachments/assets/ff7bc48d-3edc-4e1f-9f88-3bfe4ed66d04)
![image](https://github.com/user-attachments/assets/95a5a7b5-57e6-472c-969e-ae4ea771efc5)

While in the graphql test, we get the link from the index:
![image](https://github.com/user-attachments/assets/3e8cf659-e3da-42ff-b28c-f314bb42b082)

Furthermore, as far as I understand it without the @link it is not federation v2, but with the recent changes it is neither v1. So federation is currently unusable.

@jmartisk could you have a look pls? Or maybe @RoKKim?

**Comment by robp94** [comment] 2024-08-02 09:16
I did a bit more research on this, as far as I found out there is apollo federation and open federation. Open federation tries to be compatible with apollo.

For federation v2 apollo needs the @link directive. In wundergraph which uses open federation @link is not needed.

We use rover cli to combine our graphs and test them. Even if we add the @link manually we still need to make sure that the old directives are deleted like @key, and we import the ones from apollo.

In my opinion, we will need more config options to define what federation the user needs. V1? V2? apollo vs open. Since open should be compatible, apollo maybe we start with only that. Furthermore, depending on the version of v2 different directives are supported. As included in @link implementation.

**Comment by SimFlensted** [comment] 2024-08-07 07:55
Just wanna add to this issue.
We are having problems that I believe are caused by the lack of federation v2 support. We are getting the following build error in federation: `Invalid definition for directive "@key": argument "fields" should have type "_FieldSet!" but found type "FieldSet!"`, which I believe is caused because of a federation v1 schema using a v2 FieldSet type.
We have to use federation v2, and we also cannot get the @Link annotation working. 
@robp94 Did you find a workaround for adding this link, or did you do it manually in the schema (outside the generated one)?

**Comment by robp94** [comment] 2024-08-07 08:08
@SimFlensted since federation v2 needs many other changes in our schema, we replace `FieldSet` with `_FieldSet` on the fly in the apollo gateway and stick with v1 for the moment.

**Comment by SimFlensted** [comment] 2024-08-07 09:04
@robp94 Alright, thanks for a quick response! Unfortunately we rely on running federation v2

**Comment by RoMiRoSSaN** [comment] 2024-09-13 18:43
I found problem. Quarkus smallrye graphql build not full index, and ignore some dirictives [here](https://github.com/quarkusio/quarkus/blob/main/extensions/smallrye-graphql/deployment/src/main/java/io/quarkus/smallrye/graphql/deployment/SmallRyeGraphQLProcessor.java#L286).
I did a quick fix.

To work with Apollo Rover, you need to add @Link, after which the general scheme was assembled.
```
@GraphQLApi
@Link(url = FEDERATION_SPEC_LATEST_URL, _import = {
        @Import(name = "@shareable"),
        @Import(name = "@external"),
        @Import(name = "@requires"),
        @Import(name = "@composeDirective"),
        @Import(name = "@extends"),
        @Import(name = "@authenticated"),
        @Import(name = "@inaccessible"),
        @Import(name = "@interfaceObject"),
        @Import(name = "@key"),
        @Import(name = "@override"),
        @Import(name = "@provides"),
        @Import(name = "@requiresScopes"),
        @Import(name = "@tag"),
        @Import(name = "@policy")
})
public class Api { .... }
```

**Comment by RoMiRoSSaN** [comment] 2024-09-16 11:07
fix merged into quarkus
https://github.com/quarkusio/quarkus/pull/43313

**Closed** 2024-09-16 11:11 UTC

**Comment by robp94** [comment] 2024-09-19 14:44
@jmartisk @RoMiRoSSaN I still have trouble getting this to work.

Using the quarkus code starter with this properties:

```
quarkus.smallrye-graphql.federation.enabled=true
quarkus.smallrye-graphql.schema-include-directives=true
quarkus.smallrye-graphql.events.enabled=true
quarkus.smallrye-graphql.schema-include-scalars=true
quarkus.smallrye-graphql.metrics.enabled=true
```

I get this schema:

```
"Indicates to composition that the target element is accessible only to the authenticated supergraph users."
directive @authenticated on SCALAR | OBJECT | FIELD_DEFINITION | INTERFACE | ENUM

"Indicates to composition that all uses of a particular custom type system directive in the subgraph schema should be preserved in the supergraph schema (by default, composition omits most directives from the supergraph schema)."
directive @composeDirective(name: String!) repeatable on SCHEMA

"Indicates a Bean Validation constraint"
directive @constraint(format: String, max: BigInteger, maxFloat: BigDecimal, maxLength: Int, min: BigInteger, minFloat: BigDecimal, minLength: Int, pattern: String) repeatable on ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION

"Marks the field, argument, input field or enum value as deprecated"
directive @deprecated(reason: String) on FIELD_DEFINITION | ARGUMENT_DEFINITION | ENUM_VALUE | INPUT_FIELD_DEFINITION

"""
Indicates that an object or interface definition is an extension of another definition of that same type.
If your subgraph library supports GraphQL's built-in extend keyword, do not use this directive! Instead, use extend.
"""
directive @extends on OBJECT | INTERFACE

"""
Indicates that this subgraph usually can't resolve a particular object field, but it still needs to define that field for other purposes.
This directive is always used in combination with another directive that references object fields, such as @provides or @requires.
"""
directive @external on OBJECT | FIELD_DEFINITION

"Indicates that a definition in the subgraph schema should be omitted from the router's API schema, even if that definition is also present in other subgraphs. This means that the field is not exposed to clients at all."
directive @inaccessible on SCALAR | OBJECT | FIELD_DEFINITION | ARGUMENT_DEFINITION | INTERFACE | UNION | ENUM | ENUM_VALUE | INPUT_OBJECT | INPUT_FIELD_DEFINITION

"Directs the executor to include this field or fragment only when the `if` argument is true"
directive @include(
    "Included when true."
    if: Boolean!
) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT

"""
Indicates that an object definition serves as an abstraction of another subgraph's entity interface. This abstraction enables a subgraph to automatically contribute fields to all entities that implement a particular entity interface.
During composition, the fields of every @interfaceObject are added both to their corresponding interface definition and to all entity types that implement that interface.
"""
directive @interfaceObject on OBJECT

"Designates an object type as an entity and specifies its key fields (a set of fields that the subgraph can use to uniquely identify any instance of the entity). You can apply multiple @key directives to a single entity (to specify multiple valid sets of key fields)."
directive @key(fields: federation__FieldSet!, resolvable: Boolean = true) repeatable on OBJECT | INTERFACE

"This directive links definitions from an external specification to this schema."
directive @link(as: String, for: link__Purpose, import: [link__Import], url: String!) repeatable on SCHEMA

"Indicates an Input Object is a OneOf Input Object."
directive @oneOf on INPUT_OBJECT

"""
Indicates that an object field is now resolved by this subgraph instead of another subgraph where it's also defined. This enables you to migrate a field from one subgraph to another.
You can apply @override to entity fields and fields of the root operation types (such as Query and Mutation).
"""
directive @override(from: String!, label: String) on FIELD_DEFINITION

"Indicates to composition that the target element is restricted based on authorization policies that are evaluated in a Rhai script or coprocessor."
directive @policy(policies: [[federation__Policy!]!]!) on SCALAR | OBJECT | FIELD_DEFINITION | INTERFACE | ENUM

"""
Specifies a set of entity fields that a subgraph can resolve, but only at a particular schema path (at other paths, the subgraph can't resolve those fields).
If a subgraph can always resolve a particular entity field, do not apply this directive.
Using this directive is always an optional optimization. It can reduce the total number of subgraphs that your graph router needs to communicate with to resolve certain operations, which can improve performance.
"""
directive @provides(fields: federation__FieldSet!) on FIELD_DEFINITION

"Indicates that the resolver for a particular entity field depends on the values of other entity fields that are resolved by other subgraphs. This tells the graph router that it needs to fetch the values of those externally defined fields first, even if the original client query didn't request them."
directive @requires(fields: federation__FieldSet!) on FIELD_DEFINITION

"Indicates to composition that the target element is accessible only to the authenticated supergraph users with the appropriate JWT scopes"
directive @requiresScopes(scopes: [[federation__Scope!]!]!) on SCALAR | OBJECT | FIELD_DEFINITION | INTERFACE | ENUM

"Used to specify the role required to execute a given field or operation."
directive @rolesAllowed(value: String) on FIELD_DEFINITION

"Indicates that an object type's field is allowed to be resolved by multiple subgraphs (by default in Federation 2, object fields can be resolved by only one subgraph)."
directive @shareable repeatable on OBJECT | FIELD_DEFINITION

"Directs the executor to skip this field or fragment when the `if` argument is true."
directive @skip(
    "Skipped when true."
    if: Boolean!
) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT

"Exposes a URL that specifies the behaviour of this scalar."
directive @specifiedBy(
    "The URL that specifies the behaviour of this scalar."
    url: String!
) on SCALAR

"Applies arbitrary string metadata to a schema location. Custom tooling can use this metadata during any step of the schema delivery flow, including composition, static analysis, and documentation. Apollo Studio's enterprise contracts feature uses @tag with its inclusion and exclusion filters."
directive @tag(name: String!) repeatable on SCALAR | OBJECT | FIELD_DEFINITION | ARGUMENT_DEFINITION | INTERFACE | UNION | ENUM | ENUM_VALUE | INPUT_OBJECT | INPUT_FIELD_DEFINITION

"Query root"
type Query {
    _service: _Service!
    "Say hello"
    sayHello(name: String = "World"): String
}

type _Service {
    sdl: String!
}

enum link__Purpose {
    "`EXECUTION` features provide metadata necessary for operation execution."
    EXECUTION
    "`SECURITY` features provide metadata necessary to securely resolve fields."
    SECURITY
}

"Scalar for BigDecimal"
scalar BigDecimal

"Scalar for BigInteger"
scalar BigInteger

"Scalar for FieldSet"
scalar federation__FieldSet

"Scalar for Policy"
scalar federation__Policy

"Scalar for Scope"
scalar federation__Scope

"Scalar for Import"
scalar link__Import

```

Do I need another property?

**Comment by RoMiRoSSaN** [comment] 2024-09-19 15:01
@robp94 
As I understand, this change will appear in quarkus 3.15 https://github.com/quarkusio/quarkus/pull/43313

And for it to work, you will need to set the properties
```
quarkus.smallrye-graphql.federation.enabled=true  
quarkus.smallrye-graphql.schema-include-scalars=true
quarkus.smallrye-graphql.schema-include-directives=true
# include schema { query: Query }
quarkus.smallrye-graphql.schema-include-schema-definition=true
```

and in code 
```
@GraphQLApi
@Link(url = Link.FEDERATION_SPEC_LATEST_URL, _import = {
        @Import(name = "@key"),
        // etc directives
})
public class Resource {
///
}
```

Waiting version 3.15 :)

**Comment by robp94** [comment] 2024-09-19 15:04
3.15 is already released, at least the core.

**Comment by RoMiRoSSaN** [comment] 2024-09-19 15:26
I tried it right now, this is what happens in 3.15

```
schema @link(import : ["@key"], url : "https://specs.apollo.dev/federation/v2.7"){
  query: Query
}
.....
```

**Comment by robp94** [comment] 2024-09-20 07:21
> @robp94 As I understand, this change will appear in quarkus 3.15 [quarkusio/quarkus#43313](https://github.com/quarkusio/quarkus/pull/43313)
> 
> And for it to work, you will need to set the properties
> 
> ```
> quarkus.smallrye-graphql.federation.enabled=true  
> quarkus.smallrye-graphql.schema-include-scalars=true
> quarkus.smallrye-graphql.schema-include-directives=true
> # include schema { query: Query }
> quarkus.smallrye-graphql.schema-include-schema-definition=true
> ```
> 
> and in code
> 
> ```
> @GraphQLApi
> @Link(url = Link.FEDERATION_SPEC_LATEST_URL, _import = {
>         @Import(name = "@key"),
>         // etc directives
> })
> public class Resource {
> ///
> }
> ```
> 
> Waiting version 3.15 :)

Thanks with this property rover seems to happy :) 
```
quarkus.smallrye-graphql.schema-include-schema-definition=true
```

**Comment by vitomanuguerrasoft** [comment] 2024-09-26 13:32
@robp94 I got the same error on rover using Quarkus 3.15.1

```
supergraph config loaded successfully
composing supergraph with Federation v2.9.0
error[E029]: Encountered 3 build errors while trying to build a supergraph.

Caused by:
    DIRECTIVE_DEFINITION_INVALID: [contabilita] Invalid definition for directive "@key": argument "fields" should have type "_FieldSet!" but found type "FieldSet!"
    DIRECTIVE_DEFINITION_INVALID: [contabilita] Invalid definition for directive "@requires": argument "fields" should have type "_FieldSet!" but found type "FieldSet!"
    DIRECTIVE_DEFINITION_INVALID: [contabilita] Invalid definition for directive "@provides": argument "fields" should have type "_FieldSet!" but found type "FieldSet!"

        The subgraph schema you provided is invalid. See https://www.apollographql.com/docs/federation/errors/ for more information on resolving build errors. 
```

In my schema I still have FieldSet without the underscore.

Here my properties:

```
quarkus.smallrye-graphql.federation.enabled=true
quarkus.smallrye-graphql.schema-include-directives=true
quarkus.smallrye-graphql.events.enabled=true
quarkus.smallrye-graphql.schema-include-scalars=true
quarkus.smallrye-graphql.metrics.enabled=true
quarkus.smallrye-graphql.schema-include-schema-definition=true
```

**Comment by robp94** [comment] 2024-09-26 13:37
@vitomanuguerrasoft do you have the annotation on the api?

**Comment by robp94** [comment] 2024-09-26 13:45
I haven‘t tested it with multiple classes yet only with a simple example. Maybe @RoMiRoSSaN  or @jmartisk can answer that.

**Comment by RoMiRoSSaN** [comment] 2024-09-26 21:10
@vitomanuguerrasoft 

Hi. No, make one empty class that will contain `@Link` and that's it. More than 1 time there will be an error.
Here is a very primitive example of a federation that works with Apollo.
https://github.com/RoMiRoSSaN/apollo-smallrye
I haven't worked with Apollo router, but everything seems to be working correctly.

**Comment by vitomanu96** [comment] 2024-09-26 21:24
@RoMiRoSSaN The issue now seems to be resolved. Thank you for the support!
