### ISSUE TITLE
quarkus 3.1.0 Final native mode build error

### ISSUE THREAD

**Issue by KeremSirma** [smallrye/smallrye-graphql#1845] opened 2023-06-01 09:14 UTC
at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:153)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:104)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureFlowsGraphCreated(MethodTypeFlow.java:83)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.getOrCreateMethodFlowsGraph(MethodTypeFlow.java:65)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultVirtualInvokeTypeFlow.java:109)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:562)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis$1.run(PointsToAnalysis.java:488)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
        at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: 

**com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: io.opentelemetry.api.trace.Span. This error is reported at image build time because class io.smallrye.graphql.cdi.tracing.TracingService is registered for linking at image build time by command line
        at parsing io.smallrye.graphql.cdi.tracing.TracingService.afterExecute(TracingService.java:52)**

        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2518)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:110)

and my dependencies:
      <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-graphql</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client-reactive</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client-reactive-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-graphql-client</artifactId>
        </dependency>

**Comment by jmartisk** [comment] 2023-06-01 09:51
Seems it's trying to include the TracingService in the image even though you don't have the OpenTelemetry extension installed... I'll see how to fix it. As a possible workaround, I assume you could add the OpenTelemetry extension

**Comment by jmartisk** [comment] 2023-06-01 10:28
Hmm, I can't reproduce this. I tried compiling in native mode an app with SmallRye GraphQL, but no OpenTelemetry, and it worked properly. There must be something different in your setup that causes the `io.smallrye.graphql.cdi.tracing.TracingService` class to be considered reachable. Does your application contain any references to that class? Could you make a slimmed down reproducer?

The current logic in Quarkus is that the `TracingService`'s ServiceLoader entry is only added when the class `io.opentracing.Tracer` is reachable, see https://github.com/quarkusio/quarkus/blob/3.1.0.Final/extensions/smallrye-graphql/deployment/src/main/java/io/quarkus/smallrye/graphql/deployment/SmallRyeGraphQLProcessor.java#L207 which is wrong, this check should be based on something from OpenTelemetry instead (we recently replaced OpenTracing support with OpenTelemetry), interestingly the TracingService seems to still work in native when I add OpenTelemetry. So we've found a potentital bug, but it doesn't explain the error you're seeing.

**Comment by KeremSirma** [comment] 2023-06-01 10:32
I am not using OpenTelemetry. I am using quarkus-smallrye-opentracing. Swagger etc. There is no error anywhere. It's only in graphql.

**Comment by jmartisk** [comment] 2023-06-01 10:41
Ah right, so that explains it. It is because of the line that I linked. That line doesn't actually add the ServiceLoader entry as I mistakenly said, but it marks it for reflection, effectively still adding it into the native image when OpenTracing is present, even though OpenTelemetry is not. So we will have to fix that line in Quarkus. I'll submit a fix asap

**Comment by jmartisk** [comment] 2023-06-01 10:43
If you're able to, I'd be glad if you could verify that the fix works for you, if you remove this particular line: https://github.com/quarkusio/quarkus/blob/3.1.0.Final/extensions/smallrye-graphql/deployment/src/main/java/io/quarkus/smallrye/graphql/deployment/SmallRyeGraphQLProcessor.java#L207 (I think we actually don't need it at all)

and build your own snapshot of Quarkus  and then build your application using that snapshot

**Comment by KeremSirma** [comment] 2023-06-01 10:44
> 

Thanks a lot!

**Comment by jmartisk** [comment] 2023-06-07 05:11
fixed on Quarkus side via https://github.com/quarkusio/quarkus/pull/33769, so this will be resolved in 3.1.1 and 3.2.0

**Closed** 2023-06-07 05:11 UTC
