### ISSUE TITLE
EventingService.afterExecute sometimes executed twice

### ISSUE THREAD

**Issue by computerlove** [smallrye/smallrye-graphql#1455] opened 2022-06-27 09:12 UTC
We have an EventingService logging responsetimes:
```java
private static final Map<String, Long> requestTimes = new ConcurrentHashMap<>();

@Override
public void beforeExecute(Context context) {
    requestTimes.put(context.getExecutionId(), currentTimeMillis());
}

@Override
public void afterExecute(Context context) {
    Long startTime = requestTimes.remove(context.getExecutionId());
    log.info("response time " + context.getExecutionId() + " " + calculate(startTime) );
}
```

After upgrading to Quarkus 2.10.0 `afterExecute` is executed twice for some `Context`s. 
Our application fires of ~5 graphql requests at the same time, and it seems random which one is triggering double  execution of `afterExecute`

**Comment by phillip-kruger** [comment] 2022-06-27 09:30
interesting. This is a bug, let me have a look.

**Comment by phillip-kruger** [comment] 2022-06-27 09:31
Do you perhaps have a reproducer ?

**Comment by computerlove** [comment] 2022-06-27 10:16
Haven't had time yet, will make one soon!

**Comment by phillip-kruger** [comment] 2022-06-28 01:26
I had a quick look, I can not see anything obvious, so a reproducer would help a lot. Thanks :)

**Comment by computerlove** [comment] 2022-06-28 08:10
Made a crude [reproducer](https://github.com/computerlove/smallrye-gql-issue-1455-reproducer)
The frequency of the incidents is higher when the client aborts the request before it has finished. 

Run server from root with mvn quarkus:dev, then start client from its folder the same way.

**Comment by phillip-kruger** [comment] 2022-06-30 05:05
Just some feedback, your reproducer recreates the issue perfectly, however, I am not sure how to fix this. I am going to discuss this with @cescoffier tomorrow and hopefully get a fix in for this a.s.a.p.

**Comment by cescoffier** [comment] 2022-06-30 05:33
@phillip-kruger do you know where this callback is invoked?

**Comment by phillip-kruger** [comment] 2022-06-30 05:38
Here: https://github.com/smallrye/smallrye-graphql/blob/94164da0950780e066c25f836ee7b34232f0340b/server/implementation/src/main/java/io/smallrye/graphql/execution/ExecutionService.java#L176

I tried:

- memoize()
- Removing Uni and just use the underlying `CompletionStage`

In both cases this still happen

I also checked the `onTermination` and `onCancelation` but they are also called twice.

**Comment by cescoffier** [comment] 2022-06-30 05:42
Hum, the Uni emits a single event (item, failure or cancellation (not handled in your case, BTW). So, are you sure that the `writeAsync` method is not called twice?

**Comment by phillip-kruger** [comment] 2022-06-30 05:47
Let me double check that. Hold on.

**Comment by phillip-kruger** [comment] 2022-06-30 06:16
No, `writeAsync` is called only one time.

**Comment by cescoffier** [comment] 2022-06-30 06:49
so either the completion stage is totally broken and emits twice, or there is something really wrong.

Add a `.log()` just after the creation of the Uni with the completion stage.

**Comment by cescoffier** [comment] 2022-07-01 05:58
@phillip-kruger I quick debug session showed me that `writeAsync` is called many (many) times, sometimes with the same SmallRye Context. 

It leads to calling the callback multiple times, as each execution receives a result dispatched using the callback.

**Comment by phillip-kruger** [comment] 2022-07-01 06:57
Really ? My debugging showed writeAsync called ones (per executionId) but then the result is sometimes received multiple times. You can also see the `beforeExecute` event are always only called once.

**Comment by cescoffier** [comment] 2022-07-01 07:02
I didn't check the execution Id (only the context reference). I will check once back.

**Comment by phillip-kruger** [comment] 2022-07-20 00:28
@cescoffier this still happens with 2.10.3.Final (so the context termination is not related) I still have not idea why this is happening. I'll debug some more once I have time.

**Comment by cescoffier** [comment] 2022-07-21 09:58
What an interesting issue! 

The problem is the executionId which is totally messed up because the code is called from different thread and the executed seems to be a thread local or something thread specific. 

So, basically, it's even worse than duplicated afterExecute. It may produce a totally broken result for an execution id, as the execution id was not the right one.

I "fixed" the issue by just adding this:

```java
private void writeAsync(GraphQL graphQL,
                          ExecutionInput executionInput,
                          SmallRyeContext smallRyeContext,
                          ExecutionResponseWriter writer) {
      String id = smallRyeContext.getExecutionId(); // Store the execution id
      Uni.createFrom().completionStage(() -> graphQL.executeAsync(executionInput))
              .subscribe().with(executionResult -> {
                  SmallRyeContextManager.restore(smallRyeContext);
                  // To see the issue:
                  System.out.println("what's your id? " + smallRyeContext.getExecutionId() + " =?= " + id);

                  // To fix the issue
                  smallRyeContext.setExecutionId(id);
                  // Notify after
                  eventEmitter.fireAfterExecute(smallRyeContext);

                  ExecutionResponse executionResponse = new ExecutionResponse(executionResult);
                  if (!payloadOption.equals(LogPayloadOption.off)) {
                      log.payloadOut(executionResponse.toString());
                  }
                  writer.write(executionResponse);

              }, failure -> {
                  if (failure != null) {
                      writer.fail(failure);
                  }
              });
  }
```

**Comment by phillip-kruger** [comment] 2022-07-21 11:02
Wow!! Thanks @cescoffier ! I also went down the wrong Id route but did not figure out what was wrong. 

But this probably means everything on the context is not properly propagated ?? I'll have a look about that in the morning.

Thanks for your help...

**Comment by cescoffier** [comment] 2022-07-21 11:39
I'm seeing that the computation is based on thread locals, so definitely broken as your processing involves multiple threads.

**Comment by phillip-kruger** [comment] 2022-07-21 11:40
Ok, I'll have a look tomorrow, thanks again, this helps a lot

**Comment by phillip-kruger** [comment] 2022-08-08 02:34
Good news. I fixed this in Quarkus (see above PR). @computerlove let me know once the PR is merged or on the next release if this works for you. It fixed your reproducer. Thanks. Closing here.

**Closed by phillip-kruger** 2022-08-08 02:34 UTC

**Comment by computerlove** [comment] 2022-08-09 06:53
Yep, looks good!
