### ISSUE TITLE
Generics not supported 

### ISSUE THREAD

**Issue by apellizzn** [smallrye/smallrye-graphql#511] opened 2020-11-09 10:24 UTC
Using quarkus `1.9.2.Final`
With the following code

```java
package test.graphql;

import test.graphql.dtos.PaginationInfo;

import java.util.List;

public interface Connection<T> {
    List<T> getData();
    PaginationInfo getPagination();
}
```

```java
package test.graphql;

import test.dtos.PaginationInfo;
import lombok.Builder;
import java.util.List;

@Builder
public class FruitConnection implements Connection<Fruit> {

    private List<Fruit> data;
    private PaginationInfo paginationInfo;

    @Override
    public List<Fruit> getData() {
        return data;
    }

    @Override
    public PaginationInfo getPagination() {
        return paginationInfo;
    }
}
```

```java
package test.graphql;
import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class Fruit {
    private String name;
}
```

```java
package test.graphql;

import test.dtos.PaginationInfo;
import org.eclipse.microprofile.graphql.GraphQLApi;
import org.eclipse.microprofile.graphql.Query;

import java.util.ArrayList;

@GraphQLApi
public class FruitsResource {

    @Query
    public FruitConnection all() {
        return FruitConnection.builder()
                .data(new ArrayList<>() {{ add(new Fruit("apple")); }})
                .paginationInfo(new PaginationInfo())
                .build();
    }
}
```
```java
package test.graphql.dtos;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class PaginationInfo {
    private Long total;
    private boolean hasNextPage;
    private boolean hasPreviousPage;
    private Integer pageSize;
}
```

```java
package com.camelot.avalon.graphql;

import com.camelot.avalon.dtos.PaginationInfo;

import java.util.List;

public interface Connection<T> {
    List<T> getData();
    PaginationInfo getPagination();
}
```

The compilation step throws the following error
```
2020-11-09 10:20:46,960 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.smallrye.graphql.deployment.SmallRyeGraphQLProcessor#buildExecutionService threw an exception: java.lang.IllegalArgumentException: Not a type variable!
at org.jboss.jandex.Type.asTypeVariable(Type.java:241)
at io.smallrye.graphql.schema.creator.ReferenceCreator.createReference(ReferenceCreator.java:203)
at io.smallrye.graphql.schema.creator.type.TypeCreator.addInterfaces(TypeCreator.java:153)
at io.smallrye.graphql.schema.creator.type.TypeCreator.create(TypeCreator.java:78)
at io.smallrye.graphql.schema.creator.type.TypeCreator.create(TypeCreator.java:41)
at io.smallrye.graphql.schema.SchemaBuilder.createAndAddToSchema(SchemaBuilder.java:197)
at io.smallrye.graphql.schema.SchemaBuilder.addTypesToSchema(SchemaBuilder.java:130)
```

Linked to to #281 @velias

**Comment by velias** [comment] 2020-11-09 10:32
Thanks for your report. As we just discussed in #281, the problem is patched in smallrye-graphql 1.0.15 which will be in Quarkus 1.10.0 (CR release tomorrow). Tests added through my PR #512

**Closed** 2020-11-10 05:15 UTC
